### ISSUE TITLE
Usuarios adm

### ISSUE THREAD

**Issue by byPedroCruzDev** [byPedroCruzDev/moviex#2]
Deve conter os usuarios que podem cadastrar, atualizar deletar filmes.
* Os usuarios Adm devem conter

- Id
- Nome 
- Email
- Senha
- Adm = True

**Comment by KarolaineOliveira** [comment]
//estrutura para cadastrar usuário adm//
typedef struct usuario {
    int id;
    char nome[50];
    char email[50];
    char senha[20];
    int adm;
} usuario;

//Função que verifica se um usuário é administrador ou não
int eh_admin(usuario u) {
    return u.adm == 1; // retorna 1 se o usuário é administrador, 0 caso contrário
